##### TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/devinovexia1/public_html/dev/mscportal/dev/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
     - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
   