"use client";
import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import {
  Shield,
  Mail,
  Phone,
  MapPin,
  Link,
  ChevronUp,
  Lock,
  Eye,
  Database,
  Globe,
  Cookie,
  Users,
  FileText,
} from "lucide-react";

const sections = [
  {
    id: "definitions",
    icon: <FileText className="w-4 h-4" />,
    title: "Definitions and Key Terms",
    content: (
      <ul className="space-y-3 text-sm text-muted-foreground">
        {[
          ["Cookie", "Small amount of data generated by a website and saved by your web browser. Used to identify your browser, provide analytics, and remember information such as language preference or login information."],
          ["Company", 'When this policy mentions "Company," "we," "us," or "our," it refers to MSC Accountants (36-4181 Sladeview Cres, Mississauga L5L 5R2), responsible for your information under this Privacy Policy.'],
          ["Country", "Where MSC Accountants or the owners/founders are based — Canada."],
          ["Customer", "The company, organization, or person that signs up to use the MSC Accountants Service."],
          ["Device", "Any internet-connected device such as a phone, tablet, or computer used to visit MSC Accountants."],
          ["IP Address", "A number assigned to every internet-connected device, often used to identify a device's geographic location."],
          ["Personnel", "Individuals employed by MSC Accountants or under contract to perform a service."],
          ["Personal Data", "Any information that directly or indirectly allows for the identification of a natural person."],
          ["Service", "The service provided by MSC Accountants as described on this platform."],
          ["Third-party service", "Advertisers, contest sponsors, promotional and marketing partners, and others who provide our content."],
          ["Website", "MSC Accountants's site, accessible via https://mscaccountants.com/"],
          ["You", "A person or entity that is registered with MSC Accountants to use the Services."],
        ].map(([term, def]) => (
          <li key={term} className="flex gap-2">
            <span className="font-semibold text-foreground min-w-[120px]">{term}:</span>
            <span>{def}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "collect",
    icon: <Database className="w-4 h-4" />,
    title: "What Information Do We Collect?",
    content: (
      <div className="space-y-4 text-sm text-muted-foreground">
        <p>We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, or fill out a form.</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {["Name / Username", "Phone Numbers", "Email Addresses", "Mailing Addresses", "Job Titles", "Billing Addresses", "Debit/credit card numbers", "Age", "Password"].map((item) => (
            <Badge key={item} variant="secondary" className="justify-center py-1 text-xs">{item}</Badge>
          ))}
        </div>
        <p className="font-medium text-foreground mt-4">Optional Mobile Device Data:</p>
        <ul className="space-y-2">
          <li><span className="font-medium text-foreground">Location (GPS):</span> Helps create accurate interest profiles for relevant ads.</li>
          <li><span className="font-medium text-foreground">Phonebook (Contacts):</span> Makes the platform easier to use by allowing quick access to contacts.</li>
          <li><span className="font-medium text-foreground">Camera (Pictures):</span> Allows uploading pictures directly from the platform.</li>
        </ul>
      </div>
    ),
  },
  {
    id: "third-party-enduser",
    icon: <Users className="w-4 h-4" />,
    title: "When Do We Use End User & Customer Information From Third Parties?",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>MSC Accountants will collect End User Data necessary to provide services to our customers. End users may voluntarily provide information available on social media websites. You can control how much your social media accounts share publicly through those platforms' privacy settings.</p>
        <p>We receive some information from third parties when you contact us — for example, automated fraud detection services when you submit your email. We also occasionally collect information made publicly available on social media websites.</p>
      </div>
    ),
  },
  {
    id: "sharing",
    icon: <Globe className="w-4 h-4" />,
    title: "Do We Share the Information We Collect?",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>We may share both personal and non-personal information with advertisers, promotional partners, affiliated companies, and business partners. In the event of a merger or asset sale, we may transfer your information to successors-in-interest.</p>
        <p>We may engage trusted third-party service providers for hosting, database management, email, marketing, credit card processing, and customer service. We may share personal information with these providers to enable their services.</p>
        <p>We may share log file data (including IP addresses) with analytics partners. We may also disclose information to government or law enforcement as we believe necessary to comply with legal process, protect rights, or prevent illegal activity.</p>
      </div>
    ),
  },
  {
    id: "usage",
    icon: <Eye className="w-4 h-4" />,
    title: "How Do We Use the Information We Collect?",
    content: (
      <ul className="space-y-2 text-sm text-muted-foreground list-disc list-inside">
        <li>To personalize your experience and better respond to individual needs</li>
        <li>To improve our website based on feedback</li>
        <li>To improve customer service and support</li>
        <li>To process transactions</li>
        <li>To administer contests, promotions, surveys, or other site features</li>
        <li>To send periodic emails</li>
      </ul>
    ),
  },
  {
    id: "email",
    icon: <Mail className="w-4 h-4" />,
    title: "How Do We Use Your Email Address?",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>By submitting your email address, you agree to receive emails from us. You may unsubscribe at any time via the opt-out link in each email. We only contact people who have authorized us to do so.</p>
        <p>Your email may be used for customer audience targeting on platforms like Facebook. Emails submitted solely through the order page are used only for order-related communications. Detailed unsubscribe instructions are included at the bottom of each email.</p>
      </div>
    ),
  },
  {
    id: "retention",
    icon: <Database className="w-4 h-4" />,
    title: "How Long Do We Keep Your Information?",
    content: (
      <p className="text-sm text-muted-foreground">We keep your information only as long as needed to provide our Service and fulfill the purposes described in this policy. When no longer needed and no legal or regulatory obligation requires it, we will remove it from our systems or depersonalize it.</p>
    ),
  },
  {
    id: "security",
    icon: <Lock className="w-4 h-4" />,
    title: "How Do We Protect Your Information?",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>We implement a variety of security measures to maintain the safety of your personal information. All sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and encrypted in our Payment gateway provider's database. After a transaction, private information is never kept on file.</p>
        <p>We cannot, however, guarantee absolute security against all potential breaches of our physical, technical, or managerial safeguards.</p>
      </div>
    ),
  },
  {
    id: "transfer",
    icon: <Globe className="w-4 h-4" />,
    title: "Could My Information Be Transferred to Other Countries?",
    content: (
      <p className="text-sm text-muted-foreground">MSC Accountants is incorporated in Canada. Information may be transferred to our offices or third parties located worldwide, including countries with different data protection laws. By using our service, you voluntarily consent to this trans-border transfer and hosting.</p>
    ),
  },
  {
    id: "update",
    icon: <FileText className="w-4 h-4" />,
    title: "Can I Update or Correct My Information?",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Customers have the right to request restriction of certain uses of personally identifiable information. You can contact us to: (1) update or correct your information, (2) change your communication preferences, or (3) delete personal information by cancelling your account.</p>
        <p>To protect your privacy, we may verify your identity before granting profile access or making corrections. You are responsible for maintaining your unique password and account information.</p>
      </div>
    ),
  },
  {
    id: "cookies",
    icon: <Cookie className="w-4 h-4" />,
    title: "Cookies",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>MSC Accountants uses "Cookies" to identify areas of our website you have visited. Cookies enhance performance and functionality but are non-essential. Without them, certain features like videos may be unavailable or you may need to re-enter login details each visit.</p>
        <p>Most web browsers can be set to disable cookies. However, disabling them may affect functionality. We never place Personally Identifiable Information in Cookies.</p>
        <p><span className="font-medium text-foreground">Blocking Cookies:</span> You may set your browser to block cookies, but this may prevent our website from functioning properly and could cause you to lose saved information (e.g., login details, preferences).</p>
      </div>
    ),
  },
  {
    id: "tracking",
    icon: <Globe className="w-4 h-4" />,
    title: "Tracking Technologies",
    content: (
      <div className="space-y-4 text-sm text-muted-foreground">
        <div>
          <p className="font-medium text-foreground">Google Maps API</p>
          <p className="mt-1">Used to create custom maps, searchable maps, and location-based features. Google Maps API may collect information from you and your device for security purposes, in accordance with Google's Privacy Policy.</p>
        </div>
        <div>
          <p className="font-medium text-foreground">Local Storage</p>
          <p className="mt-1">Provides web apps with methods for storing client-side data with enhanced capacity compared to cookies, without information stored in HTTP request headers.</p>
        </div>
        <div>
          <p className="font-medium text-foreground">Sessions</p>
          <p className="mt-1">We use "Sessions" to identify areas of our platform you have visited. A Session is a small piece of data stored on your device by your web browser.</p>
        </div>
        <div>
          <p className="font-medium text-foreground">Remarketing Services</p>
          <p className="mt-1">We use remarketing (retargeting) to display ads to people who have previously visited our website across other internet platforms and websites.</p>
        </div>
      </div>
    ),
  },
  {
    id: "gdpr",
    icon: <Shield className="w-4 h-4" />,
    title: "GDPR — General Data Protection Regulation",
    content: (
      <div className="space-y-4 text-sm text-muted-foreground">
        <p>GDPR is an EU-wide privacy and data protection law regulating how EU residents' data is protected. We have implemented GDPR controls as our baseline standard for all operations worldwide.</p>
        <p className="font-medium text-foreground">Data Protection Principles:</p>
        <ul className="space-y-2 list-disc list-inside">
          <li>Personal data must be processed in a fair, legal, and transparent way.</li>
          <li>Personal data should only be collected to fulfil a specific purpose and used only for that purpose.</li>
          <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
          <li>People covered by GDPR have the right to access, copy, update, delete, restrict, or move their data.</li>
        </ul>
        <p>We store all conversation and personal data for up to 6 years unless your account is deleted. Upon deletion, we dispose of all data within 60 days.</p>
      </div>
    ),
  },
  {
    id: "kids",
    icon: <Users className="w-4 h-4" />,
    title: "Kids' Privacy",
    content: (
      <p className="text-sm text-muted-foreground">We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13. If you are a parent or guardian and believe your child has provided us with Personal Data, please contact us immediately. We will take steps to remove that information from our servers.</p>
    ),
  },
  {
    id: "changes",
    icon: <FileText className="w-4 h-4" />,
    title: "Changes to Our Privacy Policy",
    content: (
      <p className="text-sm text-muted-foreground">We may change our Service and policies, and we may need to update this Privacy Policy accordingly. Unless otherwise required by law, we will notify you before changes take effect and give you an opportunity to review them. Continued use of the Service after changes go into effect means you accept the updated policy.</p>
    ),
  },
  {
    id: "governing",
    icon: <Shield className="w-4 h-4" />,
    title: "Governing Law",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>This Privacy Policy is governed by the laws of Canada without regard to its conflict of laws provisions. You consent to the exclusive jurisdiction of Canadian courts in connection with any action or dispute arising under this Privacy Policy.</p>
        <p>By using MSC Accountants or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree, you should not engage with our website or use our services.</p>
      </div>
    ),
  },
];

export default function PrivacyPolicy() {
  const [showScroll, setShowScroll] = useState(false);

  const handleScroll = (e) => {
    setShowScroll(e.target.scrollTop > 300);
  };

  const scrollToTop = () => {
    document.getElementById("privacy-scroll-area")?.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 py-10">
        {/* Header */}
        <div className="mb-10 text-center space-y-3">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-primary/10 mb-2">
            <Shield className="w-7 h-7 text-primary" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-foreground">Privacy Policy</h1>
          <Badge variant="outline" className="text-xs">Updated at April 4th, 2026</Badge>
          <p className="text-muted-foreground max-w-2xl mx-auto text-sm leading-relaxed">
            <strong>MSC Accountants</strong> ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed. By accessing or using our Service, you agree to the terms described herein.
          </p>
        </div>

        <Separator className="mb-8" />

        {/* Accordion Sections */}
        <Accordion type="multiple" className="space-y-3">
          {sections.map((section) => (
            <AccordionItem
              key={section.id}
              value={section.id}
              className="border rounded-lg px-4 bg-card shadow-sm"
            >
              <AccordionTrigger className="text-left hover:no-underline py-4">
                <div className="flex items-center gap-3">
                  <span className="text-primary">{section.icon}</span>
                  <span className="font-semibold text-sm">{section.title}</span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pb-4 pt-1">
                {section.content}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <Separator className="my-10" />

        {/* Contact Card */}
        <Card className="bg-primary/5 border-primary/20">
          <CardContent className="pt-6">
            <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
              <Mail className="w-5 h-5 text-primary" />
              Contact Us
            </h2>
            <p className="text-sm text-muted-foreground mb-4">Don't hesitate to contact us if you have any questions.</p>
            <div className="space-y-3">
              {[
                { icon: <Mail className="w-4 h-4" />, label: "Email", value: "suleman@mscaccountant.com", href: "mailto:suleman@mscaccountant.com" },
                { icon: <Phone className="w-4 h-4" />, label: "Phone", value: "+1-(416) 300 3525", href: "tel:+14163003525" },
                { icon: <Link className="w-4 h-4" />, label: "Website", value: "https://mscaccountants.com/", href: "https://mscaccountants.com/" },
                { icon: <MapPin className="w-4 h-4" />, label: "Address", value: "36-4181 Sladeview Cres, Mississauga L5L 5R2", href: null },
              ].map(({ icon, label, value, href }) => (
                <div key={label} className="flex items-start gap-3 text-sm">
                  <span className="text-primary mt-0.5">{icon}</span>
                  <div>
                    <span className="text-muted-foreground">{label}: </span>
                    {href ? (
                      <a href={href} className="text-primary hover:underline font-medium">{value}</a>
                    ) : (
                      <span className="font-medium">{value}</span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <p className="text-center text-xs text-muted-foreground mt-8">
          This Privacy Policy was created with Termify.
        </p>
      </div>
    </div>
  );
}
