import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Scale,
  Mail,
  Phone,
  Link,
  FileText,
  ShieldAlert,
  RefreshCw,
  Gavel,
  AlertTriangle,
  Users,
  Globe,
  Cookie,
  Layers,
  Lock,
  Megaphone,
  Copy,
  Pen,
} from "lucide-react";

const sections = [
  {
    id: "general",
    icon: <FileText className="w-4 h-4" />,
    title: "General Terms",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>By accessing and placing an order with Accountants Portal, you confirm that you are in agreement with and bound by these Terms & Conditions. These terms apply to the entire website and any email or other communication between you and Accountants Portal.</p>
        <p>Under no circumstances shall Accountants Portal be liable for any direct, indirect, special, incidental, or consequential damages, including loss of data or profit, arising out of the use — or inability to use — materials on this site.</p>
        <p>Accountants Portal will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the right to change prices and revise the resources usage policy at any time.</p>
      </div>
    ),
  },
  {
    id: "license",
    icon: <FileText className="w-4 h-4" />,
    title: "License",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Accountants Portal grants you a revocable, non-exclusive, non-transferable, limited license to download, install, and use the app strictly in accordance with the terms of this Agreement.</p>
        <p>These Terms & Conditions are a contract between you and Accountants Portal, the provider of the Accountants Portal website and services. If you violate any of these Terms, we reserve the right to cancel your account or block access without notice.</p>
      </div>
    ),
  },
  {
    id: "definitions",
    icon: <FileText className="w-4 h-4" />,
    title: "Definitions and Key Terms",
    content: (
      <ul className="space-y-3 text-sm text-muted-foreground">
        {[
          ["Cookie", "Small amount of data generated by a website and saved by your web browser, used to identify your browser, provide analytics, and remember information."],
          ["Company", 'When these terms mention "Company," "we," "us," or "our," it refers to Innovage Softwares Inc. (36-4181 Sladeview Cres, Mississauga L5L 5R2).'],
          ["Country", "Where Accountants Portal or its owners/founders are based — Canada."],
          ["Device", "Any internet-connected device such as a phone, tablet, or computer used to visit Accountants Portal."],
          ["Service", "The service provided by Accountants Portal as described on this platform."],
          ["Third-party service", "Advertisers, contest sponsors, promotional and marketing partners, and others who provide content or whose products may interest you."],
          ["App/Application", "Accountants Portal app, refers to the SOFTWARE PRODUCT identified above."],
          ["You", "A person or entity that is registered with Accountants Portal to use the Services."],
        ].map(([term, def]) => (
          <li key={term} className="flex gap-2">
            <span className="font-semibold text-foreground min-w-[130px]">{term}:</span>
            <span>{def}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "restrictions",
    icon: <ShieldAlert className="w-4 h-4" />,
    title: "Restrictions",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>You agree not to, and will not permit others to:</p>
        <ul className="space-y-2 list-disc list-inside">
          <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, or otherwise commercially exploit the app or make the platform available to any third party.</li>
          <li>Modify, make derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the app.</li>
          <li>Remove, alter, or obscure any proprietary notice (including copyright or trademark) of Accountants Portal or its affiliates, partners, suppliers, or licensors.</li>
        </ul>
      </div>
    ),
  },
  {
    id: "refund",
    icon: <RefreshCw className="w-4 h-4" />,
    title: "Return and Refund Policy",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Thanks for shopping at Accountants Portal. We appreciate that you like to buy the stuff we build and want to make sure you have a rewarding experience.</p>
        <p>By placing an order or making a purchase at Accountants Portal, you agree to these terms along with Accountants Portal's Privacy Policy.</p>
        <p>If, for any reason, you are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any issues you are experiencing with our product.</p>
      </div>
    ),
  },
  {
    id: "suggestions",
    icon: <Pen className="w-4 h-4" />,
    title: "Your Suggestions",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Any feedback, comments, ideas, improvements, or suggestions (collectively, "Suggestions") provided by you to Accountants Portal with respect to the app shall remain the sole and exclusive property of Accountants Portal.</p>
        <p>Accountants Portal shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or compensation to you.</p>
      </div>
    ),
  },
  {
    id: "consent",
    icon: <FileText className="w-4 h-4" />,
    title: "Your Consent",
    content: (
      <p className="text-sm text-muted-foreground">We've updated our Terms & Conditions to provide complete transparency into what is being set when you visit our site and how it's being used. By using our app, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.</p>
    ),
  },
  {
    id: "links",
    icon: <Globe className="w-4 h-4" />,
    title: "Links to Other Websites",
    content: (
      <p className="text-sm text-muted-foreground">These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by Accountants Portal. We are not responsible for the content, accuracy, or opinions expressed on such websites. When you use a link to go from our Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website is subject to that website's own rules and policies.</p>
    ),
  },
  {
    id: "cookies",
    icon: <Cookie className="w-4 h-4" />,
    title: "Cookies",
    content: (
      <p className="text-sm text-muted-foreground">Accountants Portal uses "Cookies" to identify areas of our app that you have visited. Cookies enhance performance and functionality but are non-essential. Without them, certain features may be unavailable or you may need to log in every time you visit. Most web browsers can be set to disable cookies, but this may affect your access to app functionality. We never place Personally Identifiable Information in Cookies.</p>
    ),
  },
  {
    id: "changes-terms",
    icon: <RefreshCw className="w-4 h-4" />,
    title: "Changes to Our Terms & Conditions",
    content: (
      <p className="text-sm text-muted-foreground">Accountants Portal may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement without prior notice. You may stop using the Service at any time without specifically informing Accountants Portal. If we decide to change our Terms & Conditions, we will post those changes on this page and update the modification date.</p>
    ),
  },
  {
    id: "modifications",
    icon: <Layers className="w-4 h-4" />,
    title: "Modifications & Updates to Our App",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Accountants Portal reserves the right to modify, suspend, or discontinue, temporarily or permanently, the app or any service to which it connects, with or without notice and without liability to you.</p>
        <p>Accountants Portal may provide enhancements or improvements to the features and functionality of the app, which may include patches, bug fixes, updates, upgrades, and other modifications ("Updates").</p>
        <p>Updates may modify or delete certain features and/or functionalities. You agree that all Updates will be (i) deemed an integral part of the app, and (ii) subject to the terms and conditions of this Agreement.</p>
      </div>
    ),
  },
  {
    id: "third-party",
    icon: <Globe className="w-4 h-4" />,
    title: "Third-Party Services",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>We may display, include, or make available third-party content or provide links to third-party websites or services ("Third-Party Services").</p>
        <p>Accountants Portal shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, or decency. Third-Party Services are provided solely as a convenience to you, and you access and use them entirely at your own risk.</p>
      </div>
    ),
  },
  {
    id: "termination",
    icon: <ShieldAlert className="w-4 h-4" />,
    title: "Term and Termination",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>This Agreement shall remain in effect until terminated by you or Accountants Portal. Accountants Portal may, at its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</p>
        <p>This Agreement will terminate immediately, without prior notice, if you fail to comply with any provision. Upon termination, you shall cease all use of the app and delete all copies from your computer.</p>
        <p>Termination will not limit any of Accountants Portal's rights or remedies at law or in equity in case of breach by you during the term of this Agreement.</p>
      </div>
    ),
  },
  {
    id: "copyright",
    icon: <Copy className="w-4 h-4" />,
    title: "Copyright Infringement Notice",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>If you are a copyright owner or their agent and believe any material on our app constitutes an infringement, please contact us with:</p>
        <ul className="space-y-1 list-disc list-inside">
          <li>A physical or electronic signature of the copyright owner or authorized person</li>
          <li>Identification of the material claimed to be infringing</li>
          <li>Your contact information (address, telephone number, and email)</li>
          <li>A statement of good faith belief that the use is not authorized</li>
          <li>A statement that the information is accurate and you are authorized to act on behalf of the owner</li>
        </ul>
      </div>
    ),
  },
  {
    id: "indemnification",
    icon: <Lock className="w-4 h-4" />,
    title: "Indemnification",
    content: (
      <p className="text-sm text-muted-foreground">You agree to indemnify and hold Accountants Portal and its parents, subsidiaries, affiliates, officers, employees, agents, partners, and licensors harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>
    ),
  },
  {
    id: "warranties",
    icon: <AlertTriangle className="w-4 h-4" />,
    title: "No Warranties",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>The app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. Accountants Portal expressly disclaims all warranties, whether express, implied, statutory, or otherwise, including all implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.</p>
        <p>Accountants Portal provides no warranty that the app will meet your requirements, achieve any intended results, be compatible with other software, operate without interruption, or be error-free.</p>
      </div>
    ),
  },
  {
    id: "liability",
    icon: <Scale className="w-4 h-4" />,
    title: "Limitation of Liability",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>The entire liability of Accountants Portal and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the app.</p>
        <p>To the maximum extent permitted by applicable law, Accountants Portal shall not be liable for any special, incidental, indirect, or consequential damages whatsoever, including damages for loss of profits, loss of data, business interruption, or personal injury, arising out of the use or inability to use the app.</p>
      </div>
    ),
  },
  {
    id: "severability",
    icon: <FileText className="w-4 h-4" />,
    title: "Severability",
    content: (
      <p className="text-sm text-muted-foreground">If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect. YOU AND Accountants Portal AGREE THAT ANY CAUSE OF ACTION MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
    ),
  },
  {
    id: "waiver",
    icon: <Gavel className="w-4 h-4" />,
    title: "Waiver",
    content: (
      <p className="text-sm text-muted-foreground">The failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter, nor shall a waiver of a breach constitute a waiver of any subsequent breach. No failure or delay in exercising any right or power under this Agreement shall operate as a waiver of that right or power.</p>
    ),
  },
  {
    id: "amendments",
    icon: <Pen className="w-4 h-4" />,
    title: "Amendments to this Agreement",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Accountants Portal reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect.</p>
        <p>By continuing to access or use our app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Accountants Portal.</p>
      </div>
    ),
  },
  {
    id: "intellectual-property",
    icon: <Lock className="w-4 h-4" />,
    title: "Intellectual Property",
    content: (
      <p className="text-sm text-muted-foreground">The app and its entire contents, features, and functionality are owned by Accountants Portal, its licensors, or other providers and are protected by Canadian and international copyright, trademark, patent, trade secret, and other intellectual property laws. The material may not be copied, modified, reproduced, downloaded, or distributed in any way without the express prior written permission of Accountants Portal.</p>
    ),
  },
  {
    id: "arbitration",
    icon: <Gavel className="w-4 h-4" />,
    title: "Agreement to Arbitrate",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>This section applies to any dispute except those relating to claims for injunctive or equitable relief regarding intellectual property rights. In the event of a dispute, you or Accountants Portal must give the other a Notice of Dispute in writing.</p>
        <p>Send any Notice of Dispute via email to: <a href="mailto:innovage@innovagesoft.com" className="text-primary hover:underline">innovage@innovagesoft.com</a>. Both parties will attempt to resolve disputes through informal negotiation within 60 days from the date the Notice is sent. After 60 days, either party may commence arbitration.</p>
        <p>If informal negotiation fails, disputes will be resolved exclusively by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. The prevailing party's legal costs shall be borne by the non-prevailing party.</p>
      </div>
    ),
  },
  {
    id: "submissions",
    icon: <Copy className="w-4 h-4" />,
    title: "Submissions and Privacy",
    content: (
      <p className="text-sm text-muted-foreground">In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data, or proposals, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of Accountants Portal without any compensation or credit to you. Accountants Portal may use the ideas contained in such submissions for any purposes in any medium in perpetuity.</p>
    ),
  },
  {
    id: "promotions",
    icon: <Megaphone className="w-4 h-4" />,
    title: "Promotions",
    content: (
      <p className="text-sm text-muted-foreground">Accountants Portal may, from time to time, include contests, promotions, sweepstakes, or other activities ("Promotions") that require you to submit material or information concerning yourself. All Promotions may be governed by separate rules that may contain eligibility requirements such as age and geographic location restrictions. You are responsible to read all Promotions rules to determine whether you are eligible to participate. Additional terms and conditions may apply to purchases of goods or services through the Services.</p>
    ),
  },
  {
    id: "typographical",
    icon: <AlertTriangle className="w-4 h-4" />,
    title: "Typographical Errors",
    content: (
      <p className="text-sm text-muted-foreground">In the event a product and/or service is listed at an incorrect price or with incorrect information due to a typographical error, we shall have the right to refuse or cancel any orders placed for the product or service at the incorrect price. If your credit card has already been charged for the purchase and your order is cancelled, we shall immediately issue a credit to your credit card account in the amount of the charge.</p>
    ),
  },
  {
    id: "miscellaneous",
    icon: <FileText className="w-4 h-4" />,
    title: "Miscellaneous",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>If any provision of these Terms & Conditions is found unenforceable, the remainder will continue in full force and effect. Any waiver of any provision will be effective only if in writing and signed by an authorized representative of Accountants Portal.</p>
        <p>Accountants Portal operates and controls the Accountants Portal Service from its offices in Canada. The Service is not intended for distribution to or use by any person or entity in any jurisdiction where such distribution or use would be contrary to law or regulation.</p>
      </div>
    ),
  },
  {
    id: "disclaimer",
    icon: <AlertTriangle className="w-4 h-4" />,
    title: "Disclaimer",
    content: (
      <div className="space-y-3 text-sm text-muted-foreground">
        <p>Accountants Portal is not responsible for any content, code, or any other imprecision. Accountants Portal does not provide warranties or guarantees.</p>
        <p>In no event shall Accountants Portal be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence, or other tort, arising out of or in connection with the use of the Service or its contents.</p>
        <p>The Accountants Portal Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied.</p>
      </div>
    ),
  },
];

export default function TermsCondition() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 py-10">
        {/* Header */}
        <div className="mb-10 text-center space-y-3">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-primary/10 mb-2">
            <Scale className="w-7 h-7 text-primary" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-foreground">Terms &amp; Conditions</h1>
          <Badge variant="outline" className="text-xs">Updated at April 4th, 2026</Badge>
          <p className="text-muted-foreground max-w-2xl mx-auto text-sm leading-relaxed">
            By accessing and placing an order with <strong>Accountants Portal</strong>, you confirm that you are in agreement with and bound by the terms of service outlined below. These terms apply to the entire website and any communication between you and Accountants Portal.
          </p>
        </div>

        <Separator className="mb-8" />

        {/* Accordion Sections */}
        <Accordion type="multiple" className="space-y-3">
          {sections.map((section) => (
            <AccordionItem
              key={section.id}
              value={section.id}
              className="border rounded-lg px-4 bg-card shadow-sm"
            >
              <AccordionTrigger className="text-left hover:no-underline py-4">
                <div className="flex items-center gap-3">
                  <span className="text-primary">{section.icon}</span>
                  <span className="font-semibold text-sm">{section.title}</span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pb-4 pt-1">
                {section.content}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <Separator className="my-10" />

        {/* Contact Card */}
        <Card className="bg-primary/5 border-primary/20">
          <CardContent className="pt-6">
            <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
              <Mail className="w-5 h-5 text-primary" />
              Contact Us
            </h2>
            <p className="text-sm text-muted-foreground mb-4">Don't hesitate to contact us if you have any questions.</p>
            <div className="space-y-3">
              {[
                { icon: <Mail className="w-4 h-4" />, label: "Email", value: "innovage@innovagesoft.com", href: "mailto:innovage@innovagesoft.com" },
                { icon: <Phone className="w-4 h-4" />, label: "Phone", value: "905-232-0482", href: "tel:9052320482" },
                { icon: <Link className="w-4 h-4" />, label: "Website", value: "https://innovagesoft.com", href: "https://innovagesoft.com" },
              ].map(({ icon, label, value, href }) => (
                <div key={label} className="flex items-start gap-3 text-sm">
                  <span className="text-primary mt-0.5">{icon}</span>
                  <div>
                    <span className="text-muted-foreground">{label}: </span>
                    <a href={href} className="text-primary hover:underline font-medium">{value}</a>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <p className="text-center text-xs text-muted-foreground mt-8">
          This Terms &amp; Conditions was created with Termify.io
        </p>
      </div>
    </div>
  );
}
