<?php
namespace App\Modules\Invoices\Controllers;
use App\Modules\Invoices\Models\Invoice; use App\Modules\Clients\Models\Firm; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Mpdf\Mpdf;
class Invoices {
 private function creator(){ $u=auth()->user(); abort_unless($u->hasAnyRole(['Admin','Accountant'])||$u->can('invoices.create'),403); }
 public function index(Request $r){$u=$r->user();$d=$r->validate(['type'=>'nullable|in:one_time,recurring','search'=>'nullable|string|max:100','sort'=>'nullable|in:number,issued_at,due_at,total,status','direction'=>'nullable|in:asc,desc']);$q=Invoice::with(['items','firm:id,guid,firm_name']);if(!$u->hasAnyRole(['Admin','Accountant']))$q->where('firm_id',$u->firm_id);if(!empty($d['type']))$q->where('source',$d['type']);if(!empty($d['search'])){$term=$d['search'];$q->where(function($w)use($term){$w->where('number','like',"%{$term}%")->orWhere('status','like',"%{$term}%")->orWhereHas('firm',fn($f)=>$f->where('firm_name','like',"%{$term}%"));});}$sort=$d['sort']??'issued_at';$direction=$d['direction']??'desc';return response()->json(['invoices'=>$q->orderBy($sort,$direction)->paginate(20)->withQueryString()]);}
 public function store(Request $r){$this->creator();$d=$r->validate(['firm_id'=>'required|exists:firms,id','due_at'=>'required|date|after_or_equal:today','issued_at'=>'required|date','hst_rate'=>'required|numeric|min:0|max:100','source'=>'nullable|in:recurring,one_time','items'=>'required|array|min:1','items.*.description'=>'required|string|max:255','items.*.amount'=>'required|numeric|min:0.01']);$subtotal=collect($d['items'])->sum(fn($i)=>(float)$i['amount']);$hst=round($subtotal*((float)$d['hst_rate']/100),2);$invoice=DB::transaction(function()use($d,$subtotal,$hst){$i=Invoice::create(['firm_id'=>$d['firm_id'],'created_by'=>auth()->id(),'number'=>'INV-'.now()->format('Ym').'-'.str_pad((string)(Invoice::max('id')+1),5,'0',STR_PAD_LEFT),'issued_at'=>$d['issued_at'],'due_at'=>$d['due_at'],'subtotal'=>$subtotal,'hst_rate'=>$d['hst_rate'],'hst_amount'=>$hst,'total'=>$subtotal+$hst,'source'=>$d['source']??'one_time','status'=>'issued']);$i->items()->createMany($d['items']);return $i->load('items','firm:id,guid,firm_name');});return response()->json(['invoice'=>$invoice],201);}
 public function download(Request $r,Invoice $invoice){abort_unless($r->user()->hasAnyRole(['Admin','Accountant'])||$r->user()->firm_id===$invoice->firm_id,403);$invoice->load('items','firm');$tempDir=storage_path('app/mpdf');if(!is_dir($tempDir))mkdir($tempDir,0755,true);$rate=rtrim(rtrim(number_format((float)$invoice->hst_rate,2,'.',''),'0'),'.');$html='<style>body{font-family:dejavusans;color:#1f2937}h1{color:#123b5d}table{margin-top:24px;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #d1d5db}</style><h1>Invoice '.e($invoice->number).'</h1><p><strong>Client:</strong> '.e($invoice->firm->firm_name).'</p><p><strong>Issued:</strong> '.$invoice->issued_at->format('Y-m-d').' &nbsp; <strong>Due:</strong> '.$invoice->due_at->format('Y-m-d').'</p><table width="100%"><tr><th align="left">Description</th><th align="right">Amount</th></tr>';foreach($invoice->items as $item)$html.='<tr><td>'.e($item->description).'</td><td align="right">$'.number_format($item->amount,2).' CAD</td></tr>';$html.='</table><p align="right">Subtotal: $'.number_format($invoice->subtotal,2).' CAD<br>HST/GST ('.$rate.'%): $'.number_format($invoice->hst_amount,2).' CAD<br><strong>Total: $'.number_format($invoice->total,2).' CAD</strong></p>';$pdf=new Mpdf(['tempDir'=>$tempDir]);$pdf->WriteHTML($html);return response($pdf->Output('','S'),200,['Content-Type'=>'application/pdf','Content-Disposition'=>'attachment; filename="'.$invoice->number.'.pdf"']);}
 public function payment(Request $r, Invoice $invoice){$u=$r->user();abort_unless($u->hasAnyRole(['Admin','Accountant'])||$u->firm_id===$invoice->firm_id,403);$d=$r->validate(['amount'=>'required|numeric']);abort_if($invoice->status==='paid'||(float)$d['amount']!==(float)$invoice->total,422,'Payment must match the invoice total.');$invoice->update(['status'=>'paid','paid_at'=>now()]);return response()->json(['invoice'=>$invoice->fresh(),'receipt'=>['id'=>'RCT-'.str_pad((string)$invoice->id,6,'0',STR_PAD_LEFT),'invoice_id'=>$invoice->id,'amount'=>$invoice->total,'issued_at'=>$invoice->paid_at]]);}
 public function status(Request $r, Invoice $invoice){$this->creator();$d=$r->validate(['status'=>'required|in:draft,issued,paid,overdue']);$invoice->update(['status'=>$d['status'],'paid_at'=>$d['status']==='paid'?($invoice->paid_at??now()):null]);return response()->json(['invoice'=>$invoice->fresh('firm')]);}
 public function receipt(Request $r, Invoice $invoice){$u=$r->user();abort_unless($u->hasAnyRole(['Admin','Accountant'])||$u->firm_id===$invoice->firm_id,403);abort_unless($invoice->status==='paid',404);$invoice->load('items','firm');$tempDir=storage_path('app/mpdf');if(!is_dir($tempDir))mkdir($tempDir,0755,true);$html='<style>body{font-family:dejavusans;color:#1f2937}h1{color:#123b5d}</style><h1>Payment Receipt</h1><h2>'.e($invoice->number).'</h2><p>Client: '.e($invoice->firm->firm_name).'</p><p>Paid: '.$invoice->paid_at->format('Y-m-d H:i').'</p><p><strong>Amount paid: $'.number_format($invoice->total,2).' CAD</strong></p>';$pdf=new Mpdf(['tempDir'=>$tempDir]);$pdf->WriteHTML($html);return response($pdf->Output('','S'),200,['Content-Type'=>'application/pdf','Content-Disposition'=>'attachment; filename="receipt-'.$invoice->number.'.pdf"']);}
}
