"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import useInvoiceApi from "@/api/useInvoiceApi";
export default function InvoicesPage() {
  const { list, download, downloadReceipt, updateStatus } = useInvoiceApi(); const searchParams = useSearchParams(); const clientId = searchParams.get("client"); const [data, setData] = useState(null); const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState("all"); const [sort, setSort] = useState({ key: "issued_at", direction: "desc" });
  useEffect(() => { list({ type: typeFilter === "all" ? undefined : typeFilter, search: query || undefined, sort: sort.key === "firm" || sort.key === "type" ? "issued_at" : sort.key, direction: sort.direction }).then(setData).catch(() => setData({ invoices: { data: [] } })); }, [typeFilter, query, sort]);
  const invoices = useMemo(() => { const q = query.toLowerCase(); return [...(data?.invoices?.data || [])].filter(i => (!clientId || String(i.firm_id || i.client_id || i.firm?.id) === String(clientId)) && `${i.number} ${i.firm?.firm_name || ""} ${i.status}`.toLowerCase().includes(q) && (typeFilter === "all" || (i.source || "one_time") === typeFilter)).sort((a,b) => { const av = a[sort.key] ?? a.firm?.firm_name ?? ""; const bv = b[sort.key] ?? b.firm?.firm_name ?? ""; return (String(av).localeCompare(String(bv), undefined, {numeric:true}) || 0) * (sort.direction === "asc" ? 1 : -1); }); }, [data, query, typeFilter, sort, clientId]);
  const sortBy = key => setSort(s => ({ key, direction: s.key === key && s.direction === "asc" ? "desc" : "asc" }));
  const heading = key => <button className="font-semibold hover:underline" onClick={() => sortBy(key)}>{key === "firm" ? "Client" : key === "type" ? "Type" : key.replace("_", " ")} {sort.key === key ? (sort.direction === "asc" ? "↑" : "↓") : "↕"}</button>;
  const changeStatus = async (invoice, status) => { await updateStatus(invoice.id, status); setData(d => ({...d, invoices: {...d.invoices, data: d.invoices.data.map(i => i.id === invoice.id ? {...i, status} : i)}})); };
  return <section className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Invoices & receipts</h1><p className="text-muted-foreground">Recurring services, urgent work, and client payment documents</p></div><div className="flex gap-2"><Link className="rounded border px-4 py-2" href="/business/invoices/recurring">Recurring agreements</Link><Link className="rounded bg-primary px-4 py-2 text-primary-foreground" href="/business/invoices/new">Urgent one-time invoice</Link></div></div><div className="rounded border bg-muted/30 p-4 text-sm"><strong>Billing workflow:</strong> Accountant signs a recurring agreement → invoice is posted to the client portal as a pre-notification → the bank transaction is completed → accountant updates the status manually → the invoice receipt becomes downloadable by both accountant and client.</div><div className="flex justify-end gap-2"><select aria-label="Filter invoices by type" className="rounded border p-2" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option value="all">All types</option><option value="one_time">One-Time</option><option value="recurring">Recurring</option></select><input aria-label="Search invoices" placeholder="Search invoices..." className="rounded border p-2" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="rounded border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">{heading("number")}</th><th className="p-3">{heading("firm")}</th><th className="p-3">{heading("type")}</th><th className="p-3">{heading("due_at")}</th><th className="p-3">{heading("total")}</th><th className="p-3">{heading("status")}</th><th className="p-3">Documents</th><th className="p-3">Receipt</th></tr></thead><tbody>{invoices.map(i => <tr className="border-b" key={i.id}><td className="p-3">{i.number}</td><td className="p-3">{i.firm?.firm_name}</td><td className="p-3">{i.source === "recurring" ? "Recurring" : "One-Time"}</td><td className="p-3">{String(i.due_at || "").slice(0, 10)}</td><td className="p-3">${i.total}</td><td className="p-3"><select aria-label={`Change status for ${i.number}`} value={i.status} onChange={e => changeStatus(i, e.target.value)} className="rounded border p-1"><option value="draft">Draft</option><option value="issued">Issued / notified</option><option value="paid">Paid</option><option value="overdue">Overdue</option></select></td><td className="p-3"><button className="underline" onClick={() => download(i.id)}>Invoice PDF</button></td><td className="p-3">{i.status === "paid" ? <button className="underline" onClick={() => downloadReceipt(i.id)}>Receipt PDF</button> : <span className="text-muted-foreground">Available after payment</span>}</td></tr>)}</tbody></table>{!invoices.length && <p className="p-6 text-muted-foreground">No invoices available.</p>}</div></section>;
}




